### ISSUE TITLE
2021 Plan

### ISSUE THREAD

**Issue by Ayfri** [Advanced-Command-Handler/Advanced-Command-Handler#27]
This issue lists all the things I want to make before 2021 Q2.

> _Note: **Bold** things are things that I'm not sure to do before 2021 Q2 and at all._

### Utils
- [x] Add a function to get all the missing properties from a message and a command.
- [x] Add a permissionError function.
- [x] Add some JSON I/O functions.
- [x] Add more miscellaneous functions.
- [x] Use the new `Intl.DateTimeFormatter` to format date into the Logger.
- [ ] **(`V3`) Save logger output into files.**

### Core
- [x] Add an Event class.
- [x] Add more methods to the classes.
- [ ] **(`V3`) Change system so commands (and events) will have to be subclasses from Command (and Event) class.** 
- [ ] **(`V3`) Add diverse command classes to make automated things like methods to react when something slow has to be made, to avoid repeating code.**
- [X] **Use typescript.**

### Examples
- [X] Move examples to separate repos.
- [X] Make more examples.

### Other
- [X] Be more organized with the module's updates.
- [x] **Make the wiki for GitHub.**

**Comment by Ayfri** [comment]
Typescript conversion started on [this branch](/Ayfri/advanced-command-handler/tree/typescript/).

**Comment by Ayfri** [comment]
Typescript conversion is done, not finished.

**Comment by Ayfri** [comment]
Adding permissionsError, getMissingProperties, getMissingTags, getPrefixFromMessage, isInRightChannel methods into 2.1.0.

**Comment by Dhruvin-Purohit** [comment]
> * [ ]  **Save logger output into files.**
Winston might be useful i guess!

**Comment by Ayfri** [comment]
I think I will do my own package for that, a lighter version of Winston maybe.

**Comment by Ayfri** [comment]
JSON Utils adds I/O JSON fonctions.

**Comment by Ayfri** [comment]
Moved the V3 things to a Project.
