### ISSUE TITLE
isOwner function is not a function

### ISSUE THREAD

**Issue by takefy-dev** [Advanced-Command-Handler/Advanced-Command-Handler#72]
Hey so I am not using the last update because I don't have the function isOwner. So i am using 2.2.2 because after this update their is no handler.client.isOwner('id') function is it normal or just a bug ?

**Comment by Ayfri** [comment]
It is normal, I moved this function into the [`src/utils/utils.ts`](https://github.com/Advanced-Command-Handler/Advanced-Command-Handler/blob/master/src/utils/utils.ts) file.
To use it, simply require it like this :
```js
const {isOwner} = require('advanced-command-handler');
```

**Comment by takefy-dev** [comment]
> It is normal, I moved this function into the [`src/utils/utils.ts`](https://github.com/Advanced-Command-Handler/Advanced-Command-Handler/blob/master/src/utils/utils.ts) file.
> To use it, simply require it like this :
> 
> ```js
> const {isOwner} = require('advanced-command-handler');
> ```

Thanks very much thats awfull i can updtate my handler now ;)
