### ISSUE TITLE
Help command in the default commands

### ISSUE THREAD

**Issue by fantomitechno** [Advanced-Command-Handler/Advanced-Command-Handler#74]
**Describe the solution you'd like**
I think all is in the title, it coule be usefull because the help is used on every bot

**Comment by Ayfri** [comment]
It would opinionates the handler, but, why not.

The v3 is planned to be a full rewrite with a more complete configuration, and I've changed my plan multiple times, like for now I'm making a bot in Kotlin and I love the features that the [Kord-Extensions](https://kord-extensions.docs.kotlindiscord.com/latest/) library offers ^^

**Comment by Ayfri** [comment]
Done in 6b9b721ce4456ed68cb87319d94666fea00ad6e3 ^^
