### ISSUE TITLE
Disabled command

### ISSUE THREAD

**Issue by fantomitechno** [Advanced-Command-Handler/Advanced-Command-Handler#76]
Adding in the CommandOptions a property disabled as Boolean, false by default.
It can be used to restrict a command (for example adding in the default message event that only the owner can use (yes it's look like ownerOnly but for a `disable [command]` command it look more logic to change a property like that)

**Comment by Ayfri** [comment]
You could also unload the commands and use an array of their names to keep track of which are disabled.

**Comment by fantomitechno** [comment]
Yes but I mean : when you're creating a command you want that only the devs can use it.
But if we use the OwnerOnly Tag, using an help command on this command that give informations like if it's owner only etc can't know if it's a command disabled or a full time OwnerOnly

**Comment by Ayfri** [comment]
You can also do this with what I said before.

Also : In v3 all commands will have to be subclasses of the Command class, so you could add the property to some commands and check when required if the property exists and is set to `true` for example.

**Comment by Ayfri** [comment]
Close the issue if my response resolves your suggestion ^^

**Comment by Ayfri** [comment]
Re-open if you want to discuss more about this.
