### ISSUE TITLE
Owner bypass

### ISSUE THREAD

**Issue by fantomitechno** [Advanced-Command-Handler/Advanced-Command-Handler#81]
**Describe the solution you'd like**
In the CommandHandler.create() method add a boolean for if the owners of the bot can bypass commands that require permission (or some tags as guildowneronly...)

**Comment by Ayfri** [comment]
I don't think that it could be a good idea, imagine the owner using admin only commands to destroy a guild where the bot is here and they are just a member. Or get private information etc

Maybe with a custom message event with a custom property on commands to select which have this feature.

I think that later in v3 I will search a way to modify message event without creating a new one, with callbacks or something.

**Comment by fantomitechno** [comment]
Yes I understand, but in certains occasion it's usefull to have somethink like that (for example I created a bot for someone, I have no permission on his server and to config the bot I needed some I just gived my self fake perms on the bot so I can config for him)

**Comment by Ayfri** [comment]
I think that it's too specific to be added as a feature, you should have a specific behavior for this for your bot, or maybe with a way that shows that the bot has this feature, maybe with a `bypass <command> [command-args]` command that you create. It's really important for me to have everything clear for owner & users.

**Comment by fantomitechno** [comment]
Oh didn't think about a solution like that but yes, I think I will go with that
